### ISSUE TITLE
importing document references shows as an object

### ISSUE THREAD

**Issue by mcconkiee** [jloosli/node-firestore-import-export#12]
### Expected behavior
After import, document references should be proper firestore references

![expected](https://user-images.githubusercontent.com/1483397/38054087-c1961abe-328a-11e8-9c34-ae758d2362dd.png)

### Actual behavior
After import, reference objects are actually key/values object representations of their export object
![2](https://user-images.githubusercontent.com/1483397/38054011-84d50d60-328a-11e8-8ebf-174b88d56c03.png)
### Steps to reproduce the behavior

1. export firestore db using the firestore export.js file
2. import the backup file produced in step 1 back to the db
3. All references are simply POJOs  (JSON)

**Comment by jloosli** [comment]
Which version of the module are you using? This should have been fixed in v0.7.0. Can you double check that and if it's not updated, try updating and running again?

**Comment by mcconkiee** [comment]
package reads `"version": "1.0.0",`

**Comment by mcconkiee** [comment]
sorry. that's 0.6.5 - let me updaet

**Comment by mcconkiee** [comment]
ok, i updated and tried again
`└── node-firestore-import-export@0.7.1 `
however, I am still having the same issue

**Comment by jloosli** [comment]
Strange. In a test document I have, the console looks like the following (tried to name field names the same as their type):

![screenshot-console firebase google com-2018 03 28-14-46-10](https://user-images.githubusercontent.com/617816/38055472-051312f4-3297-11e8-8b47-f4e544d1e392.png)

The resulting export looks like the following (with geopoint, timestamp, and documentReference converted to a json-friendly format):

```json
{
  "h4QbyGCocxgg1kJu823S": {
    "timestamp": {
      "__datatype__": "timestamp",
      "value": "2018-03-27T14:02:03.000Z"
    },
    "georeference": {
      "__datatype__": "geopoint",
      "value": {
        "_latitude": 12.15715,
        "_longitude": -158.2351784
      }
    },
    "string": "string",
    "boolean": true,
    "object": {
      "name": "object",
      "timestamp": {
        "__datatype__": "timestamp",
        "value": "2018-03-21T13:23:12.000Z"
      }
    },
    "number": 12351.342,
    "array": {
      "0": 1,
      "1": {
        "__datatype__": "timestamp",
        "value": "2018-03-27T18:23:23.000Z"
      }
    },
    "reference": {
      "__datatype__": "documentReference",
      "value": "organizations/oakley"
    },
    "__collections__": {}
  }
}
```

The document reference should look something like 
```json
{
  "field": {
    "__datatype__": "documentReference",
    "value": "organizations/oakley"
  }
}
```

Do you have any timestamp or geopoint fields that don't convert either? What happens if you pass the -V flag to the command? Is that showing 0.7.1 as well?

**Comment by mcconkiee** [comment]
@jloosli - completely appropriate you getting me back up  - total version problem. Makes sense i think. I had exported w/ the old version and tried to import with the current. Doing a full retry with just the current solves my problem.

THANKS

**Comment by jloosli** [comment]
Wonderful. Glad it's working for you. Let me know if you run into other problems

**Comment by jefelewis** [comment]
Is it possible to specify the datatype when importing? Specifically, GeoPoints?
